// <auto-generated />
using System;
using GlycemicTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlycemicTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616140804_AddUserProfileMetrics")]
    partial class AddUserProfileMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlycemicTracker.API.Models.DailyGlSummary", b =>
                {
                    b.Property<Guid>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("summary_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("EntryCount")
                        .HasColumnType("smallint")
                        .HasColumnName("entry_count");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("TotalGl")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("total_gl");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SummaryId");

                    b.HasIndex("UserId", "SummaryDate")
                        .IsUnique();

                    b.ToTable("daily_gl_summaries", (string)null);
                });

            modelBuilder.Entity("GlycemicTracker.API.Models.Ingredient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("BaseGI")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("base_gi");

                    b.Property<decimal?>("CaloriesPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("calories_per_100g");

                    b.Property<decimal>("CarbsPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("carbs_per_100g");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("FatPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("fat_per_100g");

                    b.Property<decimal>("FiberPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("fiber_per_100g");

                    b.Property<string>("LocalName")
                        .HasColumnType("text")
                        .HasColumnName("local_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("ProteinPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("protein_per_100g");

                    b.HasKey("IngredientId");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("GlycemicTracker.API.Models.MealEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<decimal?>("CaloriesConsumed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("calories_consumed");

                    b.Property<decimal?>("FatConsumed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("fat_consumed");

                    b.Property<decimal>("FinalGL")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("final_gl");

                    b.Property<decimal>("GramsConsumed")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("grams_consumed");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<string>("MealType")
                        .HasColumnType("text")
                        .HasColumnName("meal_type");

                    b.Property<decimal>("ModifiedGI")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("modified_gi");

                    b.Property<decimal>("NetCarbs")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("net_carbs");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("PrepMethodId")
                        .HasColumnType("smallint")
                        .HasColumnName("prep_method_id");

                    b.Property<decimal?>("ProteinConsumed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("protein_consumed");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EntryId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("PrepMethodId");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("meal_entries", (string)null);
                });

            modelBuilder.Entity("GlycemicTracker.API.Models.PreparationMethod", b =>
                {
                    b.Property<short>("PrepMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("prep_method_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("PrepMethodId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("GiMultiplier")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("gi_multiplier");

                    b.Property<string>("IconKey")
                        .HasColumnType("text")
                        .HasColumnName("icon_key");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method_name");

                    b.HasKey("PrepMethodId");

                    b.ToTable("preparation_methods", (string)null);
                });

            modelBuilder.Entity("GlycemicTracker.API.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("text")
                        .HasColumnName("activity_level");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DailyGiTarget")
                        .HasColumnType("numeric")
                        .HasColumnName("daily_gi_target");

                    b.Property<decimal>("DailyGlTarget")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("daily_gl_target");

                    b.Property<string>("DiabetesType")
                        .HasColumnType("text")
                        .HasColumnName("diabetes_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("GlycemicTracker.API.Models.MealEntry", b =>
                {
                    b.HasOne("GlycemicTracker.API.Models.Ingredient", "Ingredient")
                        .WithMany("MealEntries")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlycemicTracker.API.Models.PreparationMethod", "PrepMethod")
                        .WithMany("MealEntries")
                        .HasForeignKey("PrepMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("PrepMethod");
                });

            modelBuilder.Entity("GlycemicTracker.API.Models.Ingredient", b =>
                {
                    b.Navigation("MealEntries");
                });

            modelBuilder.Entity("GlycemicTracker.API.Models.PreparationMethod", b =>
                {
                    b.Navigation("MealEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
